<?php $__env->startSection('title', 'Export Finished Jobs'); ?>

<?php $__env->startSection('content'); ?>
   

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Stationary Request Form</div>

                 <div class="panel-body">
                    <div class="modal-body">
                       <form action="/closeJob">
                         <table class="table table-striped">
                        
                            <tr class="from-group">
                               <td><label>Item Description: </label></td>
                               <td><input id="description" type="text" class="form-control" name="description" required></td>
                            </tr>
                            <tr class="from-group">
                               <td><label>Quantity: </label></td>
                               <td><input id="quantity" type="number" class="form-control" name="quantity" required></td>
                             </tr>
                            <tr class="from-group">
                                <td><label>Reason: </label></td>
                                <td><input id="reason" type="text" class="form-control" name="reason" value="" required></td>
                            </tr>
                            <tr class="from-group">
                               <td><label>Status: </label></td>
                               <td><input id="status" type="text" class="form-control" name="status" required></td>
                            </tr>
                            <tr class="from-group">
                               <td><label>Comment: </label></td>
                               <td><input id="comment" type="text" class="form-control" name="comment" required></td>
                            </tr>
                           <tr class="from-group">
                               <td><label>Generated by: </label></td>
                               <td><input id="generate" type="text" class="form-control" name="generate" required></td>
                            </tr>
                        
                            <tr class="from-group">
                               <td></td>
                               <td>
                                    <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                               </td>
                            </tr>
                          </table>
                        </form>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</div>




<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>