<?php $__env->startSection('title', 'Finished Jobs'); ?>

<?php $__env->startSection('content'); ?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center">
						<b>Finished Jobs</b>
					</div>
					<div class="panel-body table-responsive">
						<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
							<?php if(count($jobs) > 0): ?>
								<tr>
									<th>Sr No</th>
									<th>Ticket</th>
									<th>Circuit Id</th>
									<th>Name</th>
									<th>Address</th>
									<th>Area</th>
									<th>City</th>
									<th>State</th>
									<th>Contact Details</th>
									<th>Generation Date</th>
									<th>Close Date</th>
									<th>Total Time</th>
									<th>Case Reason</th>
									<th>Trouble Description</th>
									<th>Assign To</th>
									<th>Generated By</th>
									<th>Solution Remark</th>
									<th>Closed By</th>
								</tr>
								<?php $__currentLoopData = $jobs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $job): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
									<tr>
										<td><?php echo e($loop->iteration); ?></td>
										<td><?php echo e($job->ticket); ?></td>
										<td><?php echo e($job->circuit_id); ?></td>
										<td><?php echo e(ucwords($job->name)); ?></td>
										<td><?php echo e(ucwords($job->address)); ?></td>
										<td><?php echo e(ucwords($job->area)); ?></td>
										<td><?php echo e(ucwords($job->city)); ?></td>
										<td><?php echo e(ucwords($job->state)); ?></td>
										<td><?php echo e($job->contact_details); ?></td>
										<td><?php echo e($job->created_at); ?></td>
										<td><?php echo e($job->close_date); ?></td>
										<td><?php echo e($job->total_time); ?></td>
										<td><?php echo e(ucwords($job->case_reason)); ?></td>
										<td><?php echo e(ucwords($job->trouble_description)); ?></td>
										<td><?php echo e(ucwords($job->assign_to)); ?></td>
										<td><?php echo e(ucwords($job->generated_by)); ?></td>
										<td><?php echo e(ucfirst($job->solution_remark)); ?></td>
										<td><?php echo e(ucwords($job->closed_by)); ?></td>
									</tr>
								<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
							<?php endif; ?>
						</table>
					</div>
				</div>
				<div class="text-center"><?php echo e($jobs->links()); ?></div>
				<a href="/exportFinishedJobs" class="btn btn-success pull-right">Export File</a>
			</div>
		</div>
	</div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>