<?php $__env->startSection('title', 'On-Going Jobs'); ?>

<?php $__env->startSection('content'); ?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center"><b>On-Going Jobs</b></div>
					<div class="panel-body table-responsive">
						<?php if(Auth::user()->department != 'field team'): ?>
							<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
								<?php if(count($jobs) > 0): ?>
									<tr>
										<th>Sr No</th>
										<th>Ticket</th>
										<th>Circuit Id</th>
										<th>Name</th>
										<th>Address</th>
										<th>Area</th>
										<th>City</th>
										<th>State</th>
										<th>Contact Details</th>
										<th>Generation Date</th>
										<th>Case Reason</th>
										<th>Assigned Level</th>
										<th>Assign To</th>
										<th>Generated By</th>
										<th>Troubleshoot</th>
										<th>Transferred To Level</th>
										<th>Transferred To</th>
										<th>Transferred By</th>
										<th></th>
										<th>Transfer</th>
										<th>Close</th>
									</tr>
									<?php $__currentLoopData = $jobs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $job): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
										<tr>
											<td><?php echo e($loop->iteration); ?></td>
											<td><?php echo e($job->ticket); ?></td>
											<td><?php echo e($job->circuit_id); ?></td>
											<td><?php echo e(ucwords($job->name)); ?></td>
											<td><?php echo e(ucwords($job->address)); ?></td>
											<td><?php echo e(ucwords($job->area)); ?></td>
											<td><?php echo e(ucwords($job->city)); ?></td>
											<td><?php echo e(ucwords($job->state)); ?></td>
											<td><?php echo e($job->contact_details); ?></td>
											<td><?php echo e($job->created_at); ?></td>
											<td><?php echo e(ucfirst($job->case_reason)); ?></td>
											<td><?php echo e(ucwords($job->assigned_to_level)); ?></td>
											<td><?php echo e(ucwords($job->assign_to)); ?></td>
											<td><?php echo e(ucwords($job->generated_by)); ?></td>
											<td><?php echo $job->troubleshoot; ?></td>
											<td><?php echo e(ucwords($job->transferred_to_level)); ?></td>
											<td><?php echo e(ucwords($job->transferred_to)); ?></td>
											<td><?php echo e(ucwords($job->transferred_by)); ?></td>
											<td>
												<button class="btn btn-success btn-sm" style="color: white;" data-toggle="modal" data-target="#troubleshoot" id="<?php echo e($job->ticket); ?>" onclick="troubleshootJob(this.id)">Troubleshoot</button>
											</td>
											<td>
												<button class="btn btn-info btn-sm" style="color: white;" data-toggle="modal" data-target="#transfer_job" id="<?php echo e($job->ticket); ?>" onclick="transferJob(this.id)">Transfer
												</button>
											</td>
											<td>
												<button class="btn btn-danger btn-sm" style="color: white;" data-toggle="modal" data-target="#close_job" id="<?php echo e($job->ticket); ?>/<?php echo e($job->generation_date_timestamp); ?>" onclick="clck(this.id)">X</button>
											</td>
										</tr>
									<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
								<?php endif; ?>
							</table>
						<?php else: ?>
							<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
								<tr>
									<th>Sr No</th>
									<th>Ticket</th>
									<th>Circuit Id</th>
									<th>Name</th>
									<th>Address</th>
									<th>Area</th>
									<th>City</th>
									<th>State</th>
									<th>Contact Details</th>
									<th>Generation Date</th>
									<th>Case Reason</th>
									<th>Assigned Level</th>
									<th>Assign To</th>
									<th>Generated By</th>
									<th>Transferred To Level</th>
									<th>Transferred To</th>
									<th>Transferred By</th>
									<th>Close</th>
								</tr>
								<?php $__currentLoopData = $fieldJobs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $fieldJob): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
									<tr>
										<td><?php echo e($loop->iteration); ?></td>
										<td><?php echo e($fieldJob->ticket); ?></td>
										<td><?php echo e($fieldJob->circuit_id); ?></td>
										<td><?php echo e(ucwords($fieldJob->name)); ?></td>
										<td><?php echo e(ucwords($fieldJob->address)); ?></td>
										<td><?php echo e(ucwords($fieldJob->area)); ?></td>
										<td><?php echo e(ucwords($fieldJob->city)); ?></td>
										<td><?php echo e(ucwords($fieldJob->state)); ?></td>
										<td><?php echo e($fieldJob->contact_details); ?></td>
										<td><?php echo e($fieldJob->created_at); ?></td>
										<td><?php echo e(ucfirst($fieldJob->case_reason)); ?></td>
										<td><?php echo e(ucwords($fieldJob->assigned_to_level)); ?></td>
										<td><?php echo e(ucwords($fieldJob->assign_to)); ?></td>
										<td><?php echo e(ucwords($fieldJob->generated_by)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_to_level)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_to)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_by)); ?></td>
										<td>
											<button class="btn btn-danger btn-sm" style="color: white;" data-toggle="modal" data-target="#close_job" id="<?php echo e($fieldJob->ticket); ?>/<?php echo e($fieldJob->generation_date_timestamp); ?>" onclick="clck(this.id)">X</button>
										</td>
									</tr>
								<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
							</table>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Modal -->
	  <div class="modal fade" id="close_job" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Close Job</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/closeJob" method="post">
					<?php echo e(csrf_field()); ?>

					<table class="table table-striped">
						<tr class="from-group">
							<td><label>Ticket: </label></td>
							<td><input type="text" name="ticket" id="printTicket" readonly="true" class="form-control"></td>
						</tr>
						
						<tr class="from-group">
							<td><label>Close Date: </label></td>
							<td><input type="text" class="form-control" id="closeDate" name="close_date" readonly="true"></td>
						</tr>
						<tr class="from-group">
							<td><label>Total Time: </label></td>
							<td><input type="text" name="total_time" id="total_time" class="form-control" readonly="true"></td>
						</tr>
						<tr class="from-group">
							<td><label>Trouble Descrption: </label></td>
							<td><input type="text" name="trouble_description" class="form-control"></td>
						</tr>
						<tr class="from-group">
							<td><label>Solution Remark: </label></td>
							<td><input class="form-control" type="text" name="solution_remark"></td>
						</tr>
						<tr class="from-group">
							<td><label>Closed By: </label></td>
							<td><input type="text" class="form-control" value="<?php echo e(ucwords(auth()->user()->name)); ?>" readonly="true" name="closed_by"></td>
						</tr>
						<tr class="from-group">
							<td></td>
							<td><input type="submit" name="close_job" class="btn btn-primary"></td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>

	  <!-- Modal -->
	  <div class="modal fade" id="transfer_job" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Transfer Job</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/transferJob" method="post">
					<?php echo e(csrf_field()); ?>

					<table class="table table-striped">
						<tr class="from-group">
							<td><label>Ticket: </label></td>
							<td><input type="text" name="ticket" id="printTicket1" readonly="true" class="form-control"></td>
						</tr>
						<tr class="from-group">
							<td><label>Transfer to level: </label></td>
							<td>
								<select name="transfer_to_level" class="selectpicker form-control" id="transfer_to_level" title="Transfer To">
								    <option value="3">3</option>
								    <option value="field team">Field Team</option>
								</select>
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Assign Job: </label></td>
							<td>
				                <select name="assign_job" class="selectpicker form-control" id="assign_job" title="Assign To">
				                    <option value="engineer">Engineer</option>
				                    <option value="team">Team</option>
				                </select>
				            </td>
						</tr>
						<tr class="from-group">
							<td><label>Transfer to: </label></td>
							<td id="engineer">
				            	<select class="selectpicker form-control" data-live-search="true" title="Select Engineer" name="assign_to_engineer">
					            	<?php if($engineers != null): ?>
                                        <?php $__currentLoopData = $engineers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $engineer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                            <?php if($engineer->name != 'admin'): ?>
                                            	<option value="<?php echo e($engineer->name); ?>" data-tokens="<?php echo e($engineer->name); ?>">
                                            		<?php echo e(ucwords($engineer->name)); ?>

                                            	</option>
                                            <?php endif; ?>
                                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                    <?php endif; ?>
				            	</select>
				            </td>
				            <td id="team">
				            	<select class="selectpicker form-control" data-live-search="true" title="Select Team" name="assign_to_team">
					            	<?php if($teams != null): ?>
                                        <?php $__currentLoopData = $teams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                            <option value="<?php echo e($team->department); ?>" data-tokens="<?php echo e($team->department); ?>">
                                            	<?php echo e(ucwords($team->department)); ?>

                                            </option>
                                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                    <?php endif; ?>
				            	</select>
				            </td>
						</tr>
						<tr class="from-group">
							<td><label>Transferred By: </label></td>
							<td><input type="text" class="form-control" value="<?php echo e(ucwords(auth()->user()->name)); ?>" readonly="true" name="transferred_by"></td>
						</tr>
						<tr class="from-group">
							<td></td>
							<td><input type="submit" name="transfer_job" class="btn btn-primary"></td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>

	  <!-- Modal -->
	  <div class="modal fade" id="troubleshoot" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Troubleshoot</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/troubleshootJob" method="post">
					<?php echo e(csrf_field()); ?>

					<table class="table table-striped">
						<tr class="from-group">
							<td><label>Ticket: </label></td>
							<td><input type="text" name="ticket" id="printTicket2" readonly="true" class="form-control"></td>
						</tr>
						<tr class="form-group">
							<td><label>Troubleshoot: </label></td>
							<td>
								<textarea name="troubleshoot" id="article-ckeditor">
									
								</textarea>
							</td>
						</tr>
						<tr class="from-group">
							<td></td>
							<td><input type="submit" name="troubleshoot_job" class="btn btn-primary"></td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>
	  <script type="text/javascript">
	  	function clck(clicked_id)
	  	{	
	  		var data = clicked_id.split("/")
	  	    document.getElementById("printTicket").value = data[0]
	  	    var currentdate = new Date(); 
	  	    var month = ""+(currentdate.getMonth()+1)
	  	    var date = currentdate.getDate()
	  	    if(currentdate.getDate() < 10)
	  	    	date = "0"+date
	  	    
	  	    var datetime = currentdate.getFullYear()+"-"+(month)+"-"+date+" "+currentdate.getHours() + ":"+ currentdate.getMinutes() + ":"+ currentdate.getSeconds()
	  	    document.getElementById("closeDate").value = datetime

	  	    console.log("ticket "+data[0])
	  	    console.log("generation_date_timestamp "+data[1])

			//Difference between generation_date and closing date
			var date1 = currentdate
			var date2 = data[1];
			var difference = date1.getTime() - date2;
			
	        var daysDifference = Math.floor(difference/1000/60/60/24)
	        difference -= daysDifference*1000*60*60*24

	       	var hoursDifference = Math.floor(difference/1000/60/60)
	        difference -= hoursDifference*1000*60*60

	        var minutesDifference = Math.floor(difference/1000/60)
	        difference -= minutesDifference*1000*60

	        var secondsDifference = Math.floor(difference/1000)

	     	var total_time = daysDifference + 'd ' + hoursDifference + 'h :' + minutesDifference + 'm :' + secondsDifference + 's'

	     	document.getElementById("total_time").value = total_time
	  	}

	  	function transferJob($ticket)
	  	{
	  		document.getElementById("printTicket1").value = $ticket
	  	}
	  	function troubleshootJob($ticket)
	  	{
	  		document.getElementById("printTicket2").value = $ticket
	  	}
	  	$(document).ready(function(){
	  		$("#engineer").hide()
	  		$("#team").hide()


	  		$("#assign_job").change(function(){
	  			var assign_job = $(this).val()
	  			if(assign_job == "engineer")
	  			{
	  				$("#engineer").show()
	  				$("#team").hide()
	  			}
	  			else
	  			{
	  				$("#engineer").hide()
	  				$("#team").show()
	  			}
	  		})
	  	}) 
	  </script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>