<?php $__env->startSection('title', 'Finished Jobs'); ?>

<?php $__env->startSection('content'); ?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center">
						<b>Finished Jobs</b>
					</div>
					<div class="panel-body table-responsive">
						<?php if(Auth::user()->department != 'field team'): ?>
							<form action="/deleteFinishedJobs" method="post">
								<?php echo e(csrf_field()); ?>

								<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
									<?php if(count($jobs) > 0): ?>
										<tr>
											<th>Sr No</th>
											<th>Ticket</th>
											<th>Circuit Id</th>
											<th>Name</th>
											<th>Address</th>
											<th>Area</th>
											<th>City</th>
											<th>State</th>
											<th>Contact Details</th>
											<th>Generation Date</th>
											<th>Close Date</th>
											<th>Total Time</th>
											<th>Case Reason</th>
											<th>Trouble Description</th>
											<th>Assign To</th>
											<th>Generated By</th>
											<th>Transferred To Level</th>
											<th>Transferred To</th>
											<th>Transferred By</th>
											<th>Solution Remark</th>
											<th>Closed By</th>
											<?php if(Auth::user()->user_type == 'admin'): ?>
												<th>Delete</th>
											<?php endif; ?>
										</tr>
										<?php $__currentLoopData = $jobs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $job): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
											<tr>
												<td><?php echo e($loop->iteration); ?></td>
												<td><?php echo e($job->ticket); ?></td>
												<td><?php echo e($job->circuit_id); ?></td>
												<td><?php echo e(ucwords($job->name)); ?></td>
												<td><?php echo e(ucwords($job->address)); ?></td>
												<td><?php echo e(ucwords($job->area)); ?></td>
												<td><?php echo e(ucwords($job->city)); ?></td>
												<td><?php echo e(ucwords($job->state)); ?></td>
												<td><?php echo e($job->contact_details); ?></td>
												<td><?php echo e($job->generation_date); ?></td>
												<td><?php echo e($job->close_date); ?></td>
												<td><?php echo e($job->total_time); ?></td>
												<td><?php echo e(ucwords($job->case_reason)); ?></td>
												<td><?php echo e(ucwords($job->trouble_description)); ?></td>
												<td><?php echo e(ucwords($job->assign_to)); ?></td>
												<td><?php echo e(ucwords($job->generated_by)); ?></td>
												<td><?php echo e(ucwords($job->transferred_to_level)); ?></td>
												<td><?php echo e(ucwords($job->transferred_to)); ?></td>
												<td><?php echo e(ucwords($job->transferred_by)); ?></td>
												<td><?php echo e(ucfirst($job->solution_remark)); ?></td>
												<td><?php echo e(ucwords($job->closed_by)); ?></td>
												<?php if(Auth::user()->user_type == 'admin'): ?>
													<td>
														<input type="checkbox" name="delete[]" value="<?php echo e($job->id); ?>">
													</td>
												<?php endif; ?>
											</tr>
										<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
									<?php endif; ?>
									<?php if(Auth::user()->user_type == 'admin'): ?>
										<td colspan="22"><input type="submit" name="deleteBtn" value="Delete" class="btn btn-danger pull-right"></td>
									<?php endif; ?>
								</table>
							</form>
						<?php else: ?>
							<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
							<?php if(count($fieldJobs) > 0): ?>
								<tr>
									<th>Sr No</th>
									<th>Ticket</th>
									<th>Circuit Id</th>
									<th>Name</th>
									<th>Address</th>
									<th>Area</th>
									<th>City</th>
									<th>State</th>
									<th>Contact Details</th>
									<th>Generation Date</th>
									<th>Close Date</th>
									<th>Total Time</th>
									<th>Case Reason</th>
									<th>Trouble Description</th>
									<th>Assign To</th>
									<th>Generated By</th>
									<th>Transferred To Level</th>
									<th>Transferred To</th>
									<th>Transferred By</th>
									<th>Solution Remark</th>
									<th>Closed By</th>
								</tr>
								<?php $__currentLoopData = $fieldJobs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $fieldJob): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
									<tr>
										<td><?php echo e($loop->iteration); ?></td>
										<td><?php echo e($fieldJob->ticket); ?></td>
										<td><?php echo e($fieldJob->circuit_id); ?></td>
										<td><?php echo e(ucwords($fieldJob->name)); ?></td>
										<td><?php echo e(ucwords($fieldJob->address)); ?></td>
										<td><?php echo e(ucwords($fieldJob->area)); ?></td>
										<td><?php echo e(ucwords($fieldJob->city)); ?></td>
										<td><?php echo e(ucwords($fieldJob->state)); ?></td>
										<td><?php echo e($fieldJob->contact_details); ?></td>
										<td><?php echo e($fieldJob->generation_date); ?></td>
										<td><?php echo e($fieldJob->close_date); ?></td>
										<td><?php echo e($fieldJob->total_time); ?></td>
										<td><?php echo e(ucwords($fieldJob->case_reason)); ?></td>
										<td><?php echo e(ucwords($fieldJob->trouble_description)); ?></td>
										<td><?php echo e(ucwords($fieldJob->assign_to)); ?></td>
										<td><?php echo e(ucwords($fieldJob->generated_by)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_to_level)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_to)); ?></td>
										<td><?php echo e(ucwords($fieldJob->transferred_by)); ?></td>
										<td><?php echo e(ucfirst($fieldJob->solution_remark)); ?></td>
										<td><?php echo e(ucwords($fieldJob->closed_by)); ?></td>
									</tr>
								<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
							<?php endif; ?>
						</table>
						<?php endif; ?>
					</div>
				</div>
				<div class="text-center"><?php echo e($jobs->links()); ?></div>
				<a href="/exportFinishedJobs" class="btn btn-success pull-right">Export File</a>
			</div>
		</div>
	</div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>