<?php $__env->startSection('title', 'New Job Entry'); ?>

<?php $__env->startSection('content'); ?>

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading text-center">
					<b>New Job Entry</b>
				</div>
				<div class="panel-body">
					<form action="/selectConsumer" method="get">
					    <table class="table table-striped">
					        <tr class="form-group">
					            <td>
					                <select name="consumer_type" class="form-control" required="true">
					                    <option value="">Select</option>
					                    <option value="partner">Partner</option>
					                    <option value="customer">Customer</option>
					                    <option value="reseller">Reseller</option>
					                </select>
					            </td>
					            <td>
					                <input type="text" name="consumer_id" class="form-control" required="true">
					            </td>
					            <td><input type="submit" class="btn btn-primary form-control" name="submit_name" value="GO"></td>
					        </tr>
					    </table>
					</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-body">
					<?php if($consumer != null): ?>
						<form action="/submitNewJob" method="post">
							<?php echo e(csrf_field()); ?>

							<table class="table table-striped">
								<?php if($consumer->type == 'customer'): ?>
									<tr class="form-group">
								        <td><label>Circuit Id</label></td>
								        <td>
								            <input type="text" name="circuit_id" value=" <?php echo e(ucwords($consumer->circuit_id)); ?> " class="form-control" required="true" readonly="true">
								        </td>
								    </tr>
								<?php endif; ?>
								<tr class="form-group">
							        <td><label>Name</label></td>
							        <td>
							            <input type="text" name="name" value=" <?php echo e(ucwords($consumer->name)); ?> " class="form-control" required="true" readonly="true">
							        </td>
							    </tr>
							    <tr class="form-group">
							        <td><label>Address</label></td>
							        <td>
							            <input type="text" name="address" value=" <?php echo e(ucwords($consumer->address)); ?> " class="form-control" required="true" readonly="true">
							        </td>
							    </tr>
							    <tr class="form-group">
							        <td><label>Area</label></td>
							        <td>
							            <input type="text" name="area" value="<?php echo e(ucwords($consumer->area)); ?>" class="form-control" required="true" readonly="true">
							        </td>
							    </tr>
							    <tr class="form-group">
							        <td><label>City</label></td>
							        <td>
							            <input type="text" name="city" value="<?php echo e(ucwords($consumer->city)); ?>" class="form-control" required="true" readonly="true">
							        </td>
							    </tr>
							    <tr class="form-group">
							        <td><label>State</label></td>
							        <td>
							            <input type="text" name="state" value="<?php echo e(ucwords($consumer->state)); ?>" class="form-control" required="true" readonly="true">
							        </td>
							    </tr>
							    <tr class="form-group">
							        <td><label>Contact Details</label></td>
							        <td>
							            <input type="text" name="contact_details" class="form-control" value="<?php echo e($consumer->contact_details); ?>" required="true">
							        </td>
							    </tr>
	                            <tr class="form-group">
	                                <td><label>Case Reason</label></td>
	                                <td>
	                                    <input type="text" name="case_reason" class="form-control" required="true">
	                                </td>
	                            </tr>
	                            <tr class="form-group">
						            <td>
						                <select name="assign_job" class="form-control">
						                    <option value="">Assign Job</option>
						                    <option value="engineer">Engineer</option>
						                    <option value="team">Team</option>
						                </select>
						            </td>
						            <td>
						                <input type="text" name="assign_to" class="form-control" required="true">
						            </td>
						        </tr>
						        <tr class="form-group">
						            <td><label>Generated By</label></td>
						            <td>
						                <input type="text" name="generated_by" value="<?php echo e(ucwords(auth()->user()->name)); ?>" class="form-control" required="true" readonly="true">
						            </td>
						        </tr>
	                            <input type="text" name="get_consumer_type" hidden="true" value="<?php echo e($consumer->type); ?>">

	                            <input type="string" name="generation_date" id="generation_date" readonly="true" hidden="true">
	                            
	                            <script type="text/javascript">
	                            	$(document).ready(function() {
	                            		var timestamps = new Date()
	                            		document.getElementById("generation_date").value = timestamps.getTime()	
	                            	});
	                            </script>
						        <tr class="form-group">
						            <td><label></label></td>
						            <td>
						                <input type="submit" name="submit_query" class="form-control btn btn-success" required="true">
						            </td>
						        </tr>   
							</table>
						</form>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>