 

<?php $__env->startSection('title', 'ManPower Request'); ?>

<?php $__env->startSection('content'); ?>
   
 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading text-center">ManPower Request Form
                </div>

                    <div class="panel-body">
                        <div class="modal-body">
                            <form action="/manPower" method="post">
                                <?php echo e(csrf_field()); ?>

                                <table class="table table-striped">
                                    <tr class="from-group">
                                        <td><label>Vacancy Designation: </label></td>
                                        <td><input id="vacancy_designation" type="text" class="form-control" name="vacancy_designation" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>No. of vacancy: </label></td>
                                      <td><input id="vacancy" type="number" class="form-control" name="vacancy" required pattern="([1-9\s]){1,}" title="Only numbers are allowed!"></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Reason: </label></td>
                                       <td><input id="reason" type="text" class="form-control" name="reason" value="" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Priority: </label></td>
                                       <td><input id="priority" type="text" class="form-control" name="priority" required pattern="([A-Za-z\s]){1,}" title="Only letters are allowed."></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Preferences: </label></td>
                                       <td><input id="preferences" type="text" class="form-control" name="preferences" required pattern="([A-Za-z\s]){3,}" title="Only letters are allowed"></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Qualification: </label></td>
                                      <td><input id="qualification" type="text" class="form-control" name="qualification" required pattern="([A-Za-z\s]){1,}" title="Only letters are allowed."></td>
                                    </tr>
                                
                                    <tr class="from-group">
                                      <td><label>Job Description: </label></td>
                                      <td><input id="job_description" type="text" class="form-control" name="job_description" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Generated by: </label></td>
                                      <td><input id="generated_by" type="text" class="form-control" name="generated_by" value="<?php echo e(Auth::user()->name); ?>" readonly="true" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td></td>
                                       <td>
                                         <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                         <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
               </div>            
            </div>
        </div>
    </div>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>