<?php $__env->startSection('title', 'Export Finished Jobs'); ?>

<?php $__env->startSection('content'); ?>
   

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Internet Leased Lines</div>

                    <div class="panel-body">
                        <div class="modal-body">
                            <form action="/closeJob">
                                <table class="table table-striped">
                                    <tr class="from-group">
                                      <td><label>Customer Name: </label></td>
                                      <td><input type="text" name="customer_name" id="customer_name" class="form-control" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                        
                                    <tr class="from-group">
                                       <td><label>Customer Address: </label></td>
                                       <td><input id="customer_address" type="text" class="form-control" name="address"  required></td>
                                    </tr>
                                    
                                    <tr class="from-group">
                                       <td><label>City: </label></td>
                                       <td><input id="city" type="text" class="form-control" name="city" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>State: </label></td>
                                      <td><input id="state" type="text" class="form-control" name="state" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Pincode: </label></td>
                                      <td><input id="pincode" type="tel" class="form-control" name="pincode" required pattern="^\d{6}$" ></td>
                                    </tr>
                                  
                                    <tr class="from-group">
                                       <td><label>Contact Person Name: </label></td>
                                       <td><input id="contact_person" type="text" class="form-control" name="contact_person" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Contact Person Number: </label></td>
                                       <td><input id="contact_number" type="tel" class="form-control" name="contact_number" required pattern="^\d{10}$" title="Enter 10-digits only!"></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Contact Person Email: </label></td>
                                      <td><input id="email" type="email" class="form-control" name="email" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Bandwidth Size: </label></td>
                                      <td><input id="bandwidth" type="number" class="form-control" name="bandwidth" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Feasibility Status: </label></td>
                                      <td><input id="feasiblity_status" type="text" class="form-control" name="feasiblity_status" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Fiber: </label></td>
                                      <td><input id="fiber" type="text" class="form-control" name="fiber" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Radio Frequency: </label></td>
                                      <td><input id="rf" type="text" class="form-control" name="rf" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Generated by: </label></td>
                                      <td><input id="generated_by" type="text" class="form-control" name="generate" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td></td>
                                       <td>
                                          <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                          <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                      </td>
                                    </tr>
                               </table>
                            </form>
                        </div>
                    </div>
              </div>            
         </div>
    </div>
</div>




<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>