@extends('layouts.app')

@section('title', 'Finished Jobs')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4">
				<div class="well">
					<form class="form-inline" action="/listFinishedJobs" method="get">
					    <table class="table-condensed">
					    	<tr class="form-group">
					    		<td>
			    			      	<select class="selectpicker form-control" name="consumer_type" title="Select Consumer Type" required="true">
			    						<option value="">All</option>
			    						<option value="partner">Partner</option>
			    						<option value="customer">Customer</option>
			    						<option value="reseller">Reseller</option>	
			    					</select>
					    		</td>
					    		<td>
					    			<input type="submit" class="btn btn-success form-control" name="filter" value="Search"> 
					    		</td>
					    	</tr>
					    </table>
					</form>
				</div> 
			</div>
			<div class="col-md-6"></div>
			<div class="col-md-2 col-sm-2">
				<div class="well text-center">
					<a href="/exportFinishedJobs" class="btn btn-warning">Export</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center">
						<b>Finished Jobs</b>
					</div>
					<div class="panel-body table-responsive">
						<form action="/deleteFinishedJobs" method="post">
							{{csrf_field()}}
							<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
								@if (count($jobs) > 0)
									<tr>
										<th>Sr No</th>
										<th>Ticket</th>
										<th>Circuit Id</th>
										<th>Name</th>
										<th>Address</th>
										<th>Area</th>
										<th>City</th>
										<th>State</th>
										<th>Contact Details</th>
										<th>Generation Date</th>
										<th>Close Date</th>
										<th>Total Time</th>
										<th>Case Reason</th>
										<th>Trouble Description</th>
										<th>Assign To</th>
										<th>Generated By</th>
										<th>Transferred To Level</th>
										<th>Transferred To</th>
										<th>Transferred By</th>
										<th>Solution Remark</th>
										<th>Closed By</th>
										@if (Auth::user()->user_type == 'admin')
											<th>Delete</th>
										@endif
									</tr>
									@foreach ($jobs as $job)
										<tr>
											<td>{{$loop->iteration}}</td>
											<td>{{$job->ticket}}</td>
											<td>{{$job->circuit_id}}</td>
											<td>{{ucwords($job->name)}}</td>
											<td>{{ucwords($job->address)}}</td>
											<td>{{ucwords($job->area)}}</td>
											<td>{{ucwords($job->city)}}</td>
											<td>{{ucwords($job->state)}}</td>
											<td>{{$job->contact_details}}</td>
											<td>{{$job->generation_date}}</td>
											<td>{{$job->close_date}}</td>
											<td>{{$job->total_time}}</td>
											<td>{{ucwords($job->case_reason)}}</td>
											<td>{{ucwords($job->trouble_description)}}</td>
											<td>{{ucwords($job->assign_to)}}</td>
											<td>{{ucwords($job->generated_by)}}</td>
											<td>{{ucwords($job->transferred_to_level)}}</td>
											<td>{{ucwords($job->transferred_to)}}</td>
											<td>{{ucwords($job->transferred_by)}}</td>
											<td>{{ucfirst($job->solution_remark)}}</td>
											<td>{{ucwords($job->closed_by)}}</td>
											@if (Auth::user()->user_type == 'admin')
												<td>
													<input type="checkbox" name="delete[]" value="{{$job->id}}">
												</td>
											@endif
										</tr>
									@endforeach
								@endif
								@if (Auth::user()->user_type == 'admin')
									<td colspan="22"><input type="submit" name="deleteBtn" value="Delete" class="btn btn-danger pull-right"></td>
								@endif
							</table>
						</form>
					</div>
				</div>
				<div class="text-center">{{$jobs->links()}}</div>
			</div>
		</div>
	</div>
@endsection