@extends('layouts.app')

@section('title', 'List Stationery Requests')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="well">
                    <form action="/exportStationeryRequests" method="get"> 
                        <table class="table-condensed">
                            <tr>
                                <td>
                                  <select class="form-control selectpicker" name="generated_by" id="generated_by" data-live-search="true" title="Generated By">
                                        @if (count($engineers) > 0)
                                            @foreach ($engineers as $engineer)
                                                <option data-tokens="{{$engineer->generated_by}}" value="{{$engineer->generated_by}}">{{ucwords($engineer->generated_by)}}</option>
                                            @endforeach     
                                        @endif  
                                    </select>
                                </td>
                                <td>
                                    <input placeholder="Generated Date" class="form-control" type="text" onfocus="(this.type='date')" name="generated_date" onblur="(this.type='text')">
                                </td>
                                <td>
                                  <select class="form-control selectpicker" name="status" id="status" data-live-search="true" title="Status">
                                      <option value="accepted">Accpted</option>
                                      <option value="pending">Pending</option>
                                      <option value="rejected">Rejected</option>  
                                   </select>
                                </td>
                                <td>
                                  <input type="text" name="about_item" id="about_item" class="form-control" placeholder=" Item name or description">
                                </td>
                                <td>
                                    <button type="submit" name="filter" class="btn btn-success">Search</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-3">
                <div class="well text-center">
                    <button onclick="printDiv()" class="btn btn-success">Print</button>
                    <button href="" class="btn btn-warning" id="btnExportToExcel">Download To Excel</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if (count($stationeryRequests) > 0)
                    <div class="panel panel-default">
                        <div class="panel-heading text-center"><b>Stationery Requests</b></div>
                        <div class="panel-body table-responsive">
                            <table class="table table-striped table-condensed table-bordered" style="border: 1px solid #ccc;" id="output">
                                <tr>
                                    <th>ID</th>
                                    <th>Item Description</th>
                                    <th>Quantity</th>
                                    <th>Reason</th>
                                    <th>Generated By</th>
                                    <th>Generated At</th>
                                    <th>Status</th>
                                    <th>Comment</th>
                                    <th>Edited By</th>
                                    <th>Edited At</th>                                </tr>
                                @foreach ($stationeryRequests as $stationeryRequest)
                                    <tr>
                                        <td>{{$stationeryRequest->id}}</td>
                                        <td>
                                            {{ucwords($stationeryRequest->item_description)}}
                                        </td>
                                        <td>
                                            {{ucwords($stationeryRequest->quantity)}}
                                        </td>
                                        <td>{{ucwords($stationeryRequest->reason)}}</td>
                                        <td>{{ucwords($stationeryRequest->generated_by)}}</td>
                                        <td>
                                            {{ucwords($stationeryRequest->created_at)}}
                                        </td>
                                        <td>{{ucwords($stationeryRequest->status)}}</td>
                                        <td>{{ucwords($stationeryRequest->comment)}}</td>
                                        <td>
                                            {{ucwords($stationeryRequest->edited_by)}}
                                        </td>
                                        <td>
                                            {{ucwords($stationeryRequest->updated_at)}}
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                    @else
                        <h2 class="text-center">NO DATA FOUND</h2>  
                @endif
            </div>
        </div>
    </div>

    <script type="text/javascript">
        function printDiv() {
        var divToPrint = document.getElementById('output');
        var htmlToPrint = '' +
                '<style type="text/css">' +
                'table th, td {' +
                'border:1px solid #000;' +
                'padding:0.5em;' +
                '}' +
                'table{' +
                'border-collapse: collapse;' +  
                '}'+
                'h3{'+
                'margin-left: 75%;'+
                '}'+
                '</style>'+
                '<h3>Sheng Li Telecom India Pvt Ltd</h3>'+
                '<center><h2>Stationery Requests</h2><center>';
        htmlToPrint += divToPrint.outerHTML;
        newWin = window.open("");
        newWin.document.write(htmlToPrint);
        newWin.print();
        newWin.close()
      }
    </script>
    <!--Download excel-->

    <script type="text/javascript">
        $(document).ready(function() {
            $("#btnExportToExcel").click(function(e) {
                e.preventDefault();
                //getting data from our table
                var data_type = 'data:application/vnd.ms-excel';
                var table_div = document.getElementById('output');
                var table_html = table_div.outerHTML.replace(/ /g, '%20');

                var currentdate = new Date(); 
                var month = ""+currentdate.getMonth()+1
                var date = currentdate.getDate()
                if(currentdate.getDate() < 10)
                    date = "0"+date
                
                var datetime = currentdate.getFullYear()+"-"+(month)+"-"+date

                var a = document.createElement('a');
                a.href = data_type + ', ' + table_html;
                a.download = 'stationeryRequests-' + datetime + '.xls';
                a.click();
            });
        });
    </script>
@endsection