@extends('layouts.app')

@section('title', 'List Man Power Requests')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="well">
                    <form action="/exportManPowerRequirments" method="get"> 
                        <table class="table-condensed">
                            <tr class="form-group">
                                <td>
                                    <select class="form-control selectpicker" name="designation" id="designation" data-live-search="true" title="Designation">
                                        @if (count($designations) > 0)
                                            @foreach ($designations as $designation)
                                                <option data-tokens="{{$designation->vacancy_designation}}" value="{{$designation->vacancy_designation}}">{{ucwords($designation->vacancy_designation)}}</option>
                                            @endforeach     
                                        @endif  
                                    </select>                                    
                                </td>
                                <td>
                                   <select class="form-control selectpicker" name="status" id="status" data-live-search="true" title="Status">
                                       <option value="accepted">Accpted</option>
                                       <option value="pending">Pending</option>
                                       <option value="rejected">Rejected</option>  
                                    </select> 
                                </td>
                                <td>
                                    <select class="form-control selectpicker" name="generated_by" id="generated_by" data-live-search="true" title="Generated By">
                                        @if (count($engineers) > 0)
                                            @foreach ($engineers as $engineer)
                                                <option data-tokens="{{$engineer->generated_by}}" value="{{$engineer->generated_by}}">{{ucwords($engineer->generated_by)}}</option>
                                            @endforeach     
                                        @endif  
                                    </select>
                                </td>
                                <td>
                                    <input placeholder="Generated Date" class="form-control" type="text" onfocus="(this.type='date')" name="generated_date" onblur="(this.type='text')">
                                </td>
                                <td>
                                    <button type="submit" name="filter" class="btn btn-success">Search</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-3">
                <div class="well text-center">
                    <button onclick="printDiv()" class="btn btn-success">Print</button>
                    <button href="" class="btn btn-warning" id="btnExportToExcel">Download To Excel</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if (count($manPowerRequests) > 0)
                    <div class="panel panel-default">
                        <div class="panel-heading text-center"><b>Man Power Requests</b></div>
                        <div class="panel-body table-responsive" id="output">
                            <table class="table table-striped table-condensed table-bordered" style="border: 1px solid #ccc;">
                                <tr>
                                    <th>ID</th>
                                    <th>Designation</th>
                                    <th>No of vacancy</th>
                                    <th>Reason</th>
                                    <th>Priority</th>
                                    <th>Preference</th>
                                    <th>Qualification</th>
                                    <th>Status</th>
                                    <th>Comment</th>
                                    <th>Generated By</th>
                                    <th>Created At</th>
                                    <th>Edited By</th>
                                    <th>Edited At</th>
                                    <th>Acted By</th>
                                </tr>
                                @foreach ($manPowerRequests as $manPowerRequest)
                                    <tr>
                                        <td>{{$manPowerRequest->id}}</td>
                                        <td>
                                            {{ucwords($manPowerRequest->vacancy_designation)}}
                                        </td>
                                        <td>
                                            {{ucwords($manPowerRequest->no_of_vacancy)}}
                                        </td>
                                        <td>{{ucwords($manPowerRequest->reason)}}</td>
                                        <td>{{ucwords($manPowerRequest->priority)}}</td>
                                        <td>{{ucwords($manPowerRequest->preferences)}}</td>
                                        <td>
                                            {{ucwords($manPowerRequest->qualification)}}
                                        </td>
                                        <td>{{ucwords($manPowerRequest->status)}}</td>
                                        <td>{{ucwords($manPowerRequest->comment)}}</td>
                                        <td>
                                            {{ucwords($manPowerRequest->generated_by)}}
                                        </td>
                                        <td>
                                            {{ucwords($manPowerRequest->created_at)}}
                                        </td>
                                        <td>
                                            {{ucwords($manPowerRequest->edited_by)}}
                                        </td>
                                        <td>
                                            {{ucwords($manPowerRequest->updated_at)}}
                                        </td>
                                        <td>
                                            {{ucwords($manPowerRequest->acted_by)}}
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                    @else
                        <h2 class="text-center">NO DATA FOUND</h2>  
                @endif 
            </div>
        </div>
    </div>

    <script type="text/javascript">
        function printDiv() {
            var divToPrint = document.getElementById('output');
            var htmlToPrint = '' +
                    '<style type="text/css">' +
                    'table th, td {' +
                    'border:1px solid #000;' +
                    'padding:0.5em;' +
                    '}' +
                    'table{' +
                    'border-collapse: collapse;' +  
                    '}'+
                    'h3{'+
                    'margin-left: 75%;'+
                    '}'+
                    '</style>'+
                    '<h3>Sheng Li Telecom India Pvt Ltd</h3>'+
                    '<center><h2>Man Power Requests</h2><center>';
            htmlToPrint += divToPrint.outerHTML;
            newWin = window.open("");
            newWin.document.write(htmlToPrint);
            newWin.print();
            newWin.close()
        }
    </script>
    <!--Download excel-->

    <script type="text/javascript">
        $(document).ready(function() {
            $("#btnExportToExcel").click(function(e) {
                e.preventDefault();
                //getting data from our table
                var data_type = 'data:application/vnd.ms-excel';
                var table_div = document.getElementById('output');
                var table_html = table_div.outerHTML.replace(/ /g, '%20');

                var currentdate = new Date(); 
                var month = ""+currentdate.getMonth()+1
                var date = currentdate.getDate()
                if(currentdate.getDate() < 10)
                    date = "0"+date
                
                var datetime = currentdate.getFullYear()+"-"+(month)+"-"+date

                var a = document.createElement('a');
                a.href = data_type + ', ' + table_html;
                a.download = 'ManPowerRequests-' + datetime + '.xls';
                a.click();
            });
        });
    </script>
@endsection