@extends('layouts.app')

@section('title', 'List Stationery Requests')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="well">
                    <form action="/listStationeryRequests" method="get"> 
                        <table class="table-condensed">
                            <tr>
                                <td>
                                  <select class="form-control selectpicker" name="generated_by" id="generated_by" data-live-search="true" title="Generated By">
                                        @if (count($engineers) > 0)
                                            @foreach ($engineers as $engineer)
                                                <option data-tokens="{{$engineer->generated_by}}" value="{{$engineer->generated_by}}">{{ucwords($engineer->generated_by)}}</option>
                                            @endforeach     
                                        @endif  
                                    </select>
                                </td>
                                <td>
                                    <input placeholder="Generated Date" class="form-control" type="text" onfocus="(this.type='date')" name="generated_date" onblur="(this.type='text')">
                                </td>
                                <td>
                                  <select class="form-control selectpicker" name="status" id="status" data-live-search="true" title="Status">
                                      <option value="accepted">Accpted</option>
                                      <option value="pending">Pending</option>
                                      <option value="rejected">Rejected</option>  
                                   </select>
                                </td>
                                <td>
                                  <input type="text" name="about_item" id="about_item" class="form-control" placeholder=" Item name or description">
                                </td>
                                <td>
                                    <button type="submit" name="filter" class="btn btn-success">Search</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-2">
                <div class="well text-center">
                    <a href="/exportStationeryRequests" class="btn btn-warning">Export</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if (count($stationeryRequests) > 0)
                    <div class="panel panel-default">
                        <div class="panel-heading text-center"><b>Stationery Requests</b></div>
                        <div class="panel-body table-responsive">
                            <form action="/deleteStationeryRequests" method="post">
                                {{csrf_field()}}
                                <table class="table table-striped table-condensed table-bordered" style="border: 1px solid #ccc;">
                                    <tr>
                                        <th>ID</th>
                                        <th>Item Description</th>
                                        <th>Quantity</th>
                                        <th>Reason</th>
                                        <th>Generated By</th>
                                        <th>Generated At</th>
                                        <th>Status</th>
                                        <th>Comment</th>
                                        <th>Action</th>
                                        <th>Edited By</th>
                                        <th>Edited At</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                    @foreach ($stationeryRequests as $stationeryRequest)
                                        <tr>
                                            <td>{{$stationeryRequest->id}}</td>
                                            <td>
                                                {{ucwords($stationeryRequest->item_description)}}
                                            </td>
                                            <td>
                                                {{ucwords($stationeryRequest->quantity)}}
                                            </td>
                                            <td>{{ucwords($stationeryRequest->reason)}}</td>
                                            <td>{{ucwords($stationeryRequest->generated_by)}}</td>
                                            <td>
                                                {{ucwords($stationeryRequest->created_at)}}
                                            </td>
                                            <td>{{ucwords($stationeryRequest->status)}}</td>
                                            <td>{{ucwords($stationeryRequest->comment)}}</td>
                                            <td>
                                                <a class="btn btn-primary btn-sm" style="color: white;" data-toggle="modal" data-target="#action" id="{{$stationeryRequest->id}}" onclick="action(this.id)">Action</a>
                                            </td>
                                            <td>
                                                {{ucwords($stationeryRequest->edited_by)}}
                                            </td>
                                            <td>
                                                {{ucwords($stationeryRequest->updated_at)}}
                                            </td>
                                            <td>
                                                <a class="btn btn-info btn-sm" style="color: white;" data-toggle="modal" data-target="#edit" id="{{$stationeryRequest->id}}" onclick="edit(this.id)">Edit</a>
                                            </td>
                                            <td>
                                                <input type="checkbox" name="delete[]" value="{{$stationeryRequest->id}}">
                                            </td>
                                        </tr>
                                    @endforeach
                                </table>
                                <input type="submit" class="btn btn-danger pull-right" name="deleteBtn" value="Delete">
                            </form>
                        </div>
                    </div>
                    @else
                        <h2 class="text-center">NO DATA FOUND</h2>  
                @endif
                <div class="text-center">{{$stationeryRequests->links()}}</div>  
            </div>
        </div>
    </div>
    <!-- Modal -->
      <div class="modal fade" id="job_description" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title text-center"><b>Job Description</b></h4>
            </div>
            <div class="modal-body">
                <p id="jd" style="padding: 10px;"></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
          
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="action" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title text-center"><b>Take Action</b></h4>
            </div>
            <div class="modal-body">
                <form action="/actionOnRequests" method="post">
                    {{csrf_field()}}
                    <table class="table table-striped">
                        <tr class="form-group">
                            <td>Select Action:</td>
                            <td>
                                <select class="selectpicker form-control" title="Select Action" name="action">
                                    <option value="accepted">Accept</option>
                                    <option value="rejected">Reject</option>
                                </select>
                            </td>
                        </tr>
                        <tr class="form-group">
                            <td>Comment:</td>
                            <td>
                                <textarea name="comment" class="form-control"></textarea>
                            </td>
                        </tr>
                        <tr class="form-group">
                            <td>Acted By:</td>
                            <td><input type="text" name="acted_by" class="form-control" readonly="true" value="{{ucwords(Auth::user()->name)}}"></td>
                        </tr>
                        <tr class="form-group">
                            <td></td>
                            <td>
                                <input type="hidden" name="requestId" id="requestId">
                                <input type="submit" name="submitAction" class="btn btn-success pull-right">
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
          
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="edit" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title text-center"><b>Edit</b></h4>
            </div>
            <div class="modal-body">
                <form action="/editStationeryRequest" method="post">
                 {{csrf_field()}}
                  <table class="table table-striped">
                     <tr class="from-group">
                        <td><label>Item Description: </label></td>
                        <td>
                          <textarea id="item_description" class="form-control" name="item_description"  cols="30" rows="2"></textarea>
                        </td>
                     </tr>
                     <tr class="from-group">
                        <td><label>Quantity: </label></td>
                        <td><input id="quantity" type="number" class="form-control" name="quantity"  min="1" title="Only number is allowed!"></td>
                      </tr>
                     <tr class="from-group">
                         <td><label>Reason: </label></td>
                         <td><input id="reason" type="text" class="form-control" name="reason" value="" ></td>
                     </tr>
                    <tr class="from-group">
                        <td><label>Edited by: </label></td>
                        <td><input id="edited_by" type="text" class="form-control" name="edited_by" value="{{Auth::user()->name}}" readonly="true" ></td>
                     </tr>
                 
                     <tr class="from-group">
                        <td></td>
                        <td>
                             <input type="hidden" name="requestId" id="requestId1">
                             <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                        </td>
                     </tr>
                   </table>
                 </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
          
        </div>
      </div>
      <script type="text/javascript">
        function action(id)
        {
            document.getElementById("requestId").value = id
        }

        function edit(id)
        {
            document.getElementById("requestId1").value = id
        }
      </script>
@endsection