@extends('layouts.app')

@section('title', 'Stationery request')

@section('content')
   
 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Stationary Request Form</div>

                 <div class="panel-body">
                    <div class="modal-body">
                       <form action="/stationery" method="post">
                        {{csrf_field()}}
                         <table class="table table-striped">
                            <tr class="from-group">
                               <td><label>Item Description: </label></td>
                               <td><input id="item_description" type="text" class="form-control" name="item_description" required></td>
                            </tr>
                            <tr class="from-group">
                               <td><label>Quantity: </label></td>
                               <td><input id="quantity" type="number" class="form-control" name="quantity" required min="1" title="Only number is allowed!"></td>
                             </tr>
                            <tr class="from-group">
                                <td><label>Reason: </label></td>
                                <td><input id="reason" type="text" class="form-control" name="reason" value="" required></td>
                            </tr>
                           <tr class="from-group">
                               <td><label>Generated by: </label></td>
                               <td><input id="generated_by" type="text" class="form-control" name="generated_by" value="{{Auth::user()->name}}" readonly="true" required></td>
                            </tr>
                        
                            <tr class="from-group">
                               <td></td>
                               <td>
                                    <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                               </td>
                            </tr>
                          </table>
                        </form>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</div>




@endsection
