@extends('layouts.app')

@section('title', 'ILL form')

@section('content')
   

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Internet Leased Lines</div>

                    <div class="panel-body">
                        <div class="modal-body">
                            <form action="/closeJob">
                                <table class="table table-striped">
                                    <tr class="from-group">
                                      <td><label>Customer Name: </label></td>
                                      <td><input type="text" name="customer_name" id="customer_name" class="form-control" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                        
                                    <tr class="from-group">
                                       <td><label>Bandwidth size: </label></td>
                                       <td><input id="bandwidth_size" type="text" class="form-control" name="@extends('layouts.app')

@section('title', 'ILL form')

@section('content')
   

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Internet Leased Lines</div>

                    <div class="panel-body">
                        <div class="modal-body">
                            <form action="/closeJob">
                                <table class="table table-striped">
                                    <tr class="from-group">
                                      <td><label>Customer Name: </label></td>
                                      <td><input type="text" name="customer_name" id="customer_name" class="form-control" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                        
                                    <tr class="from-group">
                                       <td><label>Bandwidth Size: </label></td>
                                       <td><input id="bandwidth_size" type="number" class="form-control" name="bandwidth_size"  required></td>
                                    </tr>
                                    
                                    <tr class="from-group">
                                       <td><label>Order value: </label></td>
                                       <td><input id="order_value" type="number" class="form-control" name="order_value" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Job ID: </label></td>
                                      <td><input id="job_id" type="text" class="form-control" name="job_id" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Capex: </label></td>
                                      <td><input id="capex" type="text" class="form-control" name="capex" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Opex: </label></td>
                                      <td><input id="opex" type="text" class="form-control" name="opex" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Operator involved: </label></td>
                                      <td><input id="operator_involved" type="text" class="form-control" name="operator_involved" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Miscellaneous  expenses: </label></td>
                                      <td><input id="miscellaneous_expenses" type="text" class="form-control" name="miscellaneous_expenses" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Comment: </label></td>
                                      <td><input id="comment" type="text" class="form-control" name="comment" required></td>
                                    </tr>
                                   
                                    <tr class="from-group">
                                      <td><label>Generated by: </label></td>
                                      <td><input id="generated_by" type="text" class="form-control" name="generate" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td></td>
                                       <td>
                                          <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                          <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                      </td>
                                    </tr>
                               </table>
                            </form>
                        </div>
                    </div>
              </div>            
         </div>
    </div>
</div>




@endsection
"  required></td>
                                    </tr>
                                    
                                    <tr class="from-group">
                                       <td><label>City: </label></td>
                                       <td><input id="city" type="text" class="form-control" name="city" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>State: </label></td>
                                      <td><input id="state" type="text" class="form-control" name="state" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Pincode: </label></td>
                                      <td><input id="pincode" type="tel" class="form-control" name="pincode" required pattern="^\d{6}$" ></td>
                                    </tr>
                                  
                                    <tr class="from-group">
                                       <td><label>Contact Person Name: </label></td>
                                       <td><input id="contact_name" type="text" class="form-control" name="contact_name" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Contact Person Number: </label></td>
                                       <td><input id="contact_number" type="tel" class="form-control" name="contact_number" required pattern="^\d{10}$" title="Enter 10-digits only!"></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Contact Person Email: </label></td>
                                      <td><input id="contact_email" type="email" class="form-control" name="contact_email" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Bandwidth Size: </label></td>
                                      <td><input id="bandwidth_size" type="number" class="form-control" name="bandwidth_size" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Feasibility Status: </label></td>
                                      <td><input id="feasiblity_status" type="text" class="form-control" name="feasiblity_status" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Fiber: </label></td>
                                      <td><input id="fiber" type="text" class="form-control" name="fiber" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Radio Frequency: </label></td>
                                      <td><input id="rf" type="text" class="form-control" name="rf" required ></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Generated by: </label></td>
                                      <td><input id="generated_by" type="text" class="form-control" name="generate" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td></td>
                                       <td>
                                          <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                          <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                      </td>
                                    </tr>
                               </table>
                            </form>
                        </div>
                    </div>
              </div>            
         </div>
    </div>
</div>




@endsection
