@extends('layouts.app')
@section('title', 'Approval Note')

@section('content')
   

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Approval Note</div>

                    <div class="panel-body">
                        <div class="modal-body">
                            <form action="/closeJob">
                                <table class="table table-striped">
                                    <tr class="from-group">
                                      <td><label>Customer Name: </label></td>
                                      <td><input type="text" name="customer_name" id="customer_name" class="form-control" required  pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Generated by: </label></td>
                                      <td><input id="generated_by" type="text" class="form-control" name="generated_by" required></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td><label>Bandwidth Size: </label></td>
                                       <td><input id="bandwidth_size" type="number" min="1" class="form-control" name="bandwidth_size"  required></td>
                                    </tr>
                                    
                                    <tr class="from-group">
                                       <td><label>Order value: </label></td>
                                       <td><input id="order_value" type="number" min="1" class="form-control" name="order_value" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Job ID: </label></td>
                                      <td><input id="job_id" type="text" class="form-control" name="job_id" required  pattern="([A-Za-z0-9\s]){1,}" title="Special Characters not allowed."></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Capex: </label></td>
                                      <td><input id="capex" type="number" min="1" class="form-control" name="capex" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Opex: </label></td>
                                      <td><input id="opex" type="number" min="1" class="form-control" name="opex" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Operator involved: </label></td>
                                      <td><input id="operator_involved" type="text" class="form-control" name="operator_involved" required pattern="([A-Za-z\s]){3,}" title="Only letters are allowed.Minimum 3 letters required."></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Miscellaneous  expenses: </label></td>
                                      <td><input id="miscellaneous_expenses" type="number" min="1" class="form-control" name="miscellaneous_expenses" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Comment: </label></td>
                                      <td><input id="comment" type="text" class="form-control" name="comment" required></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Approved by: </label></td>
                                      <td><select name="approved_by" class="form-control">
                                          <option value="approved_hod">Approved by HOD</option>
                                          <option value="approved_ceo"> Approved by CEO</option>
                                      </select></td>
                                    </tr>
                                    <tr class="from-group">
                                      <td><label>Approval Remark: </label></td>
                                      <td><input id="approval_remark" type="text" class="form-control" name="approval_remark" required pattern="([A-Za-z0-9\s]){1,}"></td>
                                    </tr>
                                    <tr class="from-group">
                                       <td></td>
                                       <td>
                                          <button type="clear" name="clear" class="btn btn-danger">Clear!</button>
                                          <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                      </td>
                                    </tr>
                               </table>
                            </form>
                        </div>
                    </div>
              </div>            
         </div>
    </div>
</div>




@endsection
