@extends('layouts.app')

@section('title', 'Internet Leased Line Reports')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-7">
				<div class="well">
					<form action="/exportNewIllRequests" method="get">
						<table class="table-condensed">
							<tr class="form-group">
								<td>
									<select class="form-control selectpicker" name="job_id" id="job_id1" data-live-search="true" title="Job Id">
										@if (count($ill_requests) > 0)
									        @foreach ($ill_requests as $ill_request)
									            @if ($ill_request->job_id != null)
									            	<option data-tokens="{{$ill_request->job_id}}" value="{{$ill_request->job_id}}">{{ucwords($ill_request->job_id)}}
									            	</option>
									            @endif
									        @endforeach     
									    @endif
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="customer_name" id="customer_name1" data-live-search="true" title="Customer Name">
										@if (count($customers) > 0)
									        @foreach ($customers as $customer)
									            @if ($customer->customer_name != null)
									            	<option data-tokens="{{$customer->customer_name}}" value="{{$customer->customer_name}}">{{ucwords($customer->customer_name)}}
									            	</option>
									            @endif
									        @endforeach     
									    @endif
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="contact_person_name" id="contact_person_name" data-live-search="true" title="Cont. P. Name">
										@if (count($contact_person_names) > 0)
									        @foreach ($contact_person_names as $contact_person_name)
									            @if ($contact_person_name->contact_person_name != null)
									            	<option data-tokens="{{$contact_person_name->contact_person_name}}" value="{{$contact_person_name->contact_person_name}}">{{ucwords($contact_person_name->contact_person_name)}}
									            	</option>
									            @endif
									        @endforeach     
									    @endif
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="customer_city" id="customer_city" data-live-search="true" title="City">
										@if (count($cities) > 0)
									        @foreach ($cities as $city)
									            @if ($city->customer_city != null)
									            	<option data-tokens="{{$city->customer_city}}" value="{{$city->customer_city}}">{{ucwords($city->customer_city)}}
									            	</option>
									            @endif
									        @endforeach     
									    @endif
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="feasibility_status" id="feasibility_status" title="Feasibility">
										<option value="no">No</option>
										<option value="not decided">Not Decided</option>
									</select>
								</td>
								<td>
									<button type="submit" name="filter" class="btn btn-info">Search</button>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
			<div class="col-5-md">
				<div class="well pull-right">
					<button href="" class="btn btn-warning" id="btnExportToExcel">Download To Excel</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				@if (count($ill_requests) > 0)
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<b>ILL New Connections Request</b>
						</div>
						<div class="panel-body table-responsive">
							<table class="table table-striped table-bordered table-condensed" style="border: 1px solid #ccc;" id="output">
								<tr>
									<th>Sr. No</th>
									<th>Job Id</th>
									<th>Customer Name</th>
									<th>Customer Address</th>
									<th>City</th>
									<th>State</th>
									<th>Pincode</th>
									<th>Cont. P. Name</th>
									<th>Cont. P. Number</th>
									<th>Cont. P. Email</th>
									<th>Bandwidth Size</th>
									<th>Generated By</th>
									<th>Feasible</th>
									<th>Fiber</th>
									<th>Rf</th>
								</tr>
								@foreach ($ill_requests as $request)
									<tr>
										<td>{{$loop->iteration}}</td>
										<td>{{ ucwords($request->job_id) }}</td>
										<td>{{ ucwords($request->customer_name) }}</td>
										<td>{{ ucwords($request->customer_address) }}</td>
										<td>{{ ucwords($request->customer_city) }}</td>
										<td>{{ ucwords($request->customer_state) }}</td>
										<td>{{ ucwords($request->pincode) }}</td>
										<td>{{ ucwords($request->contact_person_name) }}</td>
										<td>{{ ucwords($request->contact_person_no) }}</td>
										<td>{{ ucwords($request->contact_person_email) }}</td>
										<td>{{ ucwords($request->bandwidth_size) }}</td>
										<td>{{ ucwords($request->generated_by) }}</td>
										<td>{{ ucwords($request->feasibility_status) }}</td>
										<td>{{ ucwords($request->fiber) }}</td>
										<td>{{ ucwords($request->rf) }}</td>
									</tr>
								@endforeach
							</table>
						</div>
					</div>
				@else
				    <h2 class="text-center">NO DATA FOUND</h2>	
				@endif
			</div>
		</div>
	</div>

	<!--Download excel-->

	<script type="text/javascript">
		$(document).ready(function() {
			$("#btnExportToExcel").click(function(e) {
			    //getting data from our table
			    var data_type = 'data:application/vnd.ms-excel';
			    var table_div = document.getElementById('output');
			    var table_html = table_div.outerHTML.replace(/ /g, '%20');

			    var currentdate = new Date(); 
		  	    var month = ""+currentdate.getMonth()+1
		  	    var date = currentdate.getDate()
		  	    if(currentdate.getDate() < 10)
		  	    	date = "0"+date
		  	    
		  	    var datetime = currentdate.getFullYear()+"-"+(month)+"-"+date

			    var a = document.createElement('a');
			    a.href = data_type + ', ' + table_html;
			    a.download = 'illRequests-' + datetime + '.xls';
			    a.click();
			});
		});
	</script>
@endsection
