@extends('layouts.app')

@section('title', 'New Connection')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<div class="panel-heading text-center">
						<b>Choose Product</b>
					</div>
					<div class="panel-body">
						<table class="table table-striped">
                            <tr class="form-group">
                                <td><label>Product: </label></td>
                                <td>
                                    <select name="open_form" id="open_form" class="form-control selectpicker" title="select a product" required="true">
                                        
                                        <option value="ill_form" >ILL</option>
                                        <option value="p2p_form">Manage Services</option>
                                    </select>
                                </td>
                            </tr>
                        </table>
					</div>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div id="ill_form">
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<b>Internet Leased Line Form</b>
						</div>
						<div class="panel-body">
							<form action="/internetLeasedLineConnection" method="post">
								{{ csrf_field() }}
								<table class="table-striped table">
									<tr class="form-group">
										<td><label>Customer Name:</label></td>
										<td>
											<input type="text" name="customer_name" id="customer_name" class="form-control" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Customer Address: </label></td>
										<td>
											<input id="customer_address" type="text" class="form-control" name="customer_address"  required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>City: </label></td>
										<td>
											<input id="city" type="text" class="form-control" name="city" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>State: </label></td>
										<td>
											<input id="state" type="text" class="form-control" name="state" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Pincode: </label></td>
										<td>
											<input id="pincode" type="tel" class="form-control" name="pincode" required>
										</td>
									</tr>

									<tr class="form-group">
										<td><label>Contact Person Name: </label></td>
										<td>
											<input id="contact_person_name" type="text" class="form-control" name="contact_person_name" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Contact Person Number: </label></td>
										<td>
											<input id="contact_person_number" type="tel" class="form-control" name="contact_person_number" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Contact Person Email: </label></td>
										<td>
											<input id="contact_person_email" type="email" class="form-control" name="contact_person_email" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Bandwidth Size: </label></td>
										<td>
											<input id="bandwidth_size" type="number" min="1" class="form-control" name="bandwidth_size" required >
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Priority: </label></td>
                                      	<td>
                                      		<select name="priority" id="priority" class="selectpicker form-control" title="Select priority">
                                      			<option value="fiber">Fiber</option>
                                      			<option value="rf">Rf</option>
                                      			<option value="osp">OSP</option>
                                      		</select>
                                      	</td>
									</tr>
									<tr class="form-group">
										<td><label>Generated By: </label></td>
                                      	<td>
                                      		<input type="text" name="generated_by" id="generated_by" value="{{ Auth::user()->name }}" readonly="true" class="form-control" required>
                                      	</td>
									</tr>
									<tr class="form-group">
										<td></td>
										<td>
											<button type="clear" name="clear" class="btn btn-danger">
												Clear!
											</button>
		                                    <button type="submit" name="submit" class="btn btn-primary">
		                                    	Submit
		                                    </button>
										</td>
									</tr>
								</table>
							</form>
						</div>
					</div>
				</div>

				<div id="p2p_form">
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<b>Manage Services</b>
						</div>
						<div class="panel-body">
							<form action="/p2pConnection" method="post">
								{{ csrf_field() }}
								<table class="table table-striped">
									<tr class="form-group">
										<td><label>Customer Name: </label></td>
										<td>
											<input id="customer_name" type="text" class="form-control" name="customer_name" value="" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Contact Person Name: </label></td>
										<td>
											<input id="contact_person_name" type="text" class="form-control" name="contact_person_name" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Contact Person Number: </label></td>
										<td>
											<input id="contact_person_number" type="tel" class="form-control" name="contact_person_number" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Contact Person Email: </label></td>
										<td>
											<input id="contact_person_email" type="email" class="form-control" name="contact_person_email" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>A end Address: </label></td>
										<td>
											<input id="a_end_address" type="text" class="form-control" name="a_end_address"  required>	
										</td>
									</tr>
									<tr class="form-group">
										<td><label>A end City: </label></td>
										<td>
											<input id="a_end_city" type="text" class="form-control" name="a_end_city" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>A end State: </label></td>
										<td>
											<input id="a_end_state" type="text" class="form-control" name="a_end_state" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>A end Pincode: </label></td>
										<td>
											<input id="a_end_pincode" type="tel" class="form-control" name="a_end_pincode" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>A end lat/long: </label></td>
										<td>
											<input id="a_end_lat" type="text" class="form-control" name="a_end_lat_long" required >
										</td>
									</tr>
									<tr class="form-group">
										<td><label>B end Address: </label></td>
										<td>
											<input id="b_end_address" type="text" class="form-control" name="b_end_address"  required>	
										</td>
									</tr>
									<tr class="form-group">
										<td><label>B end City: </label></td>
										<td>
											<input id="b_end_city" type="text" class="form-control" name="b_end_city" required >
										</td>
									</tr>
									<tr class="form-group">
										<td><label>B end State: </label></td>
										<td>
											<input id="b_end_state" type="text" class="form-control" name="b_end_state" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>B end Pincode: </label></td>
										<td>
											<input id="b_end_pincode" type="tel" class="form-control" name="b_end_pincode" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>B end lat/long: </label></td>
										<td>
											<input id="b_end_lat" type="text" class="form-control" name="b_end_lat_long" required >
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Network Priority: </label></td>
										<td>
											<input id="network_priority" type="text" class="form-control" name="network_priority" required>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Other Requirments: </label></td>
										<td>
											<textarea id="other_requirments" class="form-control" name="other_requirments" cols="30" rows="3"></textarea>
										</td>
									</tr>
									<tr class="form-group">
										<td><label>Generated By: </label></td>
                                      	<td>
                                      		<input type="text" name="generated_by" id="generated_by" value="{{ Auth::user()->name }}" readonly="true" class="form-control" required>
                                      	</td>
									</tr>
									<tr class="form-group">
										<td></td>
										<td>
											<button type="clear" name="clear" class="btn btn-danger">
												Clear!
											</button>
		                                    <button type="submit" name="submit" class="btn btn-primary">
		                                    	Submit
		                                    </button>
										</td>
									</tr>
								</table>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@push('scripts')
	<script type="text/javascript">
	    $(document).ready(function(){
	      $("#ill_form").hide()
	      $("#p2p_form").hide()
	        $("#open_form").change(function(){
	            var open_form = $(this).val()
	            if(open_form == 'ill_form')
	            {
	                $("#ill_form").show()
	                $("#p2p_form").hide()
	            }
	            if(open_form == 'p2p_form'){
	              $("#p2p_form").show()
	              $("#ill_form").hide() 
	            }
	        })
	    })
	</script>
	
@endpush