@extends('layouts.app')

@section('title', 'Export Feasible Areas')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-7  col-sm-7">
				<div class="well">
					<form action="/listFeasibleAreas" class="form-inline" method="get">
						<table class="table-condensed">
							<tr class="form-group">
								<td>
									<select class="form-control selectpicker" name="reseller_name" id="reseller_name" data-live-search="true" title="Reseller Name">
									    @if (count($resellers) > 0)
									        @foreach ($resellers as $reseller)
									            <option data-tokens="{{$reseller->reseller_name}}" value="{{$reseller->reseller_name}}">{{ucwords($reseller->reseller_name)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="society" id="society" data-live-search="true" title="Society">
									    @if (count($societies) > 0)
									        @foreach ($societies as $society)
									            <option data-tokens="{{$society->society}}" value="{{$society->society}}">{{ucwords($society->society)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="area" id="area" data-live-search="true" title="Area">
									    @if (count($areas) > 0)
									        @foreach ($areas as $area)
									            <option data-tokens="{{$area->area}}" value="{{$area->area}}">{{ucwords($area->area)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="switch_location" id="switch_location" data-live-search="true" title="Switch Location">
									    @if (count($switch_locations) > 0)
									        @foreach ($switch_locations as $switch_location)
									            <option data-tokens="{{$switch_location->switch_location}}" value="{{$switch_location->switch_location}}">{{ucwords($switch_location->switch_location)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="contact_person_name" id="contact_person_name" data-live-search="true" title="Contact Person Name">
									    @if (count($contact_persons) > 0)
									        @foreach ($contact_persons as $contact_person)
									            <option data-tokens="{{$contact_person->contact_person_name}}" value="{{$contact_person->contact_person_name}}">{{ucwords($contact_person->contact_person_name)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<button type="submit" name="filter" class="btn btn-info">Search</button>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
			<div class="col-md-2 col-sm-2"></div>
			<div class="col-md-3 col-sm-3">
				<div class="well text-center">
					<button onclick="printDiv()" class="btn btn-success">Print</button>
					<button href="" class="btn btn-warning" id="btnExportToExcel">Download To Excel</button>
				</div>
			</div>
		</div>
		<div class="row">
		<div class="row">
			<div class="col-md-12">
				@if (count($feasibleAreas) > 0)
					<div class="panel panel-default">
						<div class="panel-heading text-center"><b>Feasible Areas</b></div>
						<div class="panel-body table-responsive">
							<table class="table table-striped table-bordered" style="border: 1px solid #ccc;" id="output">
								<tr>
									<th>Sr. No</th>
									<th>Reseller Name</th>
									<th>Building</th>
									<th>Society</th>
									<th>Area</th>
									<th>City</th>
									<th>Switch Location</th>
									<th>Contact Person Name</th>
									<th>Contact Person Number</th>
									<th>Generated By</th>
								</tr>
								@foreach ($feasibleAreas as $feasibleArea)
									<tr>
										<td>{{$loop->iteration}}</td>
										<td>{{ucwords($feasibleArea->reseller_name)}}</td>
										<td>{{ucwords($feasibleArea->building)}}</td>
										<td>{{ucwords($feasibleArea->society)}}</td>
										<td>{{ucwords($feasibleArea->area)}}</td>
										<td>{{ucwords($feasibleArea->city)}}</td>
										<td>{{ucwords($feasibleArea->switch_location)}}</td>
										<td>
											{{ucwords($feasibleArea->contact_person_name)}}
										</td>
										<td>
											{{ucwords($feasibleArea->contact_person_number)}}
										</td>
										<td>{{ucwords($feasibleArea->generated_by)}}</td>
									</tr>
								@endforeach		
							</table>
						</div>
					</div>
					@else
						<h1 class="text-center">No RECORD FOUND</h1>
				@endif
			</div>
		</div>
	</div>

	  	<script type="text/javascript">
		function printDiv() {
        	var divToPrint = document.getElementById('output');
        	var htmlToPrint = '' +
                '<style type="text/css">' +
                'table th, td {' +
                'border:1px solid #000;' +
                'padding:0.5em;' +
                '}' +
                'table{' +
                'border-collapse: collapse;' +	
                '}'+
                'h3{'+
                'margin-left: 75%;'+
                '}'+
                '</style>'+
                '<h3>Sheng Li Telecom India Pvt Ltd</h3>'+
                '<center><h2>Feasible Areas</h2><center>';
        	htmlToPrint += divToPrint.outerHTML;
        	newWin = window.open("");
        	newWin.document.write(htmlToPrint);
        	newWin.print();
        	$(".disable").show()
        	newWin.close()
    	}
	</script>

	<!--Download excel-->

	<script type="text/javascript">
		$(document).ready(function() {
			$("#btnExportToExcel").click(function(e) {
				e.preventDefault();
			    //getting data from our table
			    var data_type = 'data:application/vnd.ms-excel';
			    var table_div = document.getElementById('output');
			    var table_html = table_div.outerHTML.replace(/ /g, '%20');

			    var currentdate = new Date(); 
		  	    var month = ""+currentdate.getMonth()+1
		  	    var date = currentdate.getDate()
		  	    if(currentdate.getDate() < 10)
		  	    	date = "0"+date
		  	    
		  	    var datetime = currentdate.getFullYear()+"-"+(month)+"-"+date

			    var a = document.createElement('a');
			    a.href = data_type + ', ' + table_html;
			    a.download = 'FeasibleAreas-' + datetime + '.xls';
			    a.click();
			});
		});
	</script>
@endsection