@extends('layouts.app')

@section('title', 'List Refunds')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center"><b>Refunds</b></div>
					<div class="panel-body table-responsive">
						<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
							@if (count($refunds) > 0)
								<tr>
									<th>Sr. No</th>
									<th>Customer Id</th>
									<th>Customer Name</th>
									<th>Bank Name</th>
									<th>Account Number</th>
									<th>Bank Branch</th>
									<th>IFSC Code</th>
									<th>Amount</th>
									<th>Reason</th>
									<th>Mail Date</th>
									<th>Assigned To</th>
									<th>Generated By</th>
									<th>Status</th>
									<th>Acted By</th>
									<th>Take Action</th>
								</tr>
								@foreach ($refunds as $refund)
									<tr>
										<td>{{$loop->iteration}}</td>
										<td>{{ucwords($refund->customer_id)}}</td>
										<td>{{ucwords($refund->customer_name)}}</td>
										<td>{{ucwords($refund->bank)}}</td>
										<td>{{ucwords($refund->account_no)}}</td>
										<td>{{ucwords($refund->branch)}}</td>
										<td>{{ucwords($refund->ifsc_no)}}</td>
										<td>{{ucwords($refund->refund_amount)}}</td>
										<td>{{ucwords($refund->reason)}}</td>
										<td>{{ucwords($refund->mail_date)}}</td>
										<td>{{ucwords($refund->assigned_to)}}</td>
										<td>{{ucwords($refund->generated_by)}}</td>
										<td>{{ucwords($refund->refund_status)}}</td>
										<td>{{ucwords($refund->granted_by)}}</td>
										<td>
											<button class="btn btn-danger btn-sm" style="color: white;" data-toggle="modal" data-target="#change_status" id="{{$refund->id}}" value="{{$refund->customer_id}}" onclick="clck(this.id, this.value)">Action</button>
										</td>
									</tr>
								@endforeach
							@endif
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
		<!-- Modal -->
	  <div class="modal fade" id="change_status" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Change Refund Status</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/changeRefundStatus" method="post">
					{{csrf_field()}}
					<table class="table table-striped">
						<tr class="form-group">
							<td><label>Refund Id:</label></td>
							<td>
								<input type="text" name="refund_id" class="form-control" readonly="true" id="refund_id">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Customer Id:</label></td>
							<td>
								<input type="text" name="customer_id" class="form-control" readonly="true" id="customer_id">
							</td>
						</tr>
						<tr class="fomr-group">
							<td><label>Refund Status</label></td>
							<td>
								<select class="selectpicker form-control" name="refund_status" required="true" title="Select Status">
									<option value="granted">Grant</option>
									<option value="rejected">Reject</option>
								</select>
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Refund Granted By</label></td>
							<td>
								<input type="text" name="refund_granted_by" class="form-control" value="{{auth()->user()->name}}" readonly="true">
							</td>
						</tr>
						<tr class="form-group">		
							<td></td>
							<td>
								<input type="submit" class="btn btn-success" value="Submit">
							</td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>
	  <script type="text/javascript">
	  	function clck(id, value)
	  	{
	  		var data = value.split("/")
	  		document.getElementById("refund_id").value = id
	  		document.getElementById("customer_id").value = value
	  	}
	  </script>
@endsection