@extends('layouts.app')

@section('title', 'List Refunds')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-7 col-sm-7">
				<div class="well">
					<form action="/listRefunds" method="get">	
						<table class="table-condensed">
							<tr class="form-group">
								<td>
									<select class="form-control selectpicker" name="customer_id" id="customer_id1" data-live-search="true" title="Customer Id">
									    @if (count($customer_id) > 0)
									        @foreach ($customer_id as $customer)
									            <option data-tokens="{{$customer->customer_id}}" value="{{$customer->customer_id}}">{{$customer->customer_id}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="customer_name" id="customer_name1" data-live-search="true" title="Customer Name">
									    @if (count($customer_name) > 0)
									        @foreach ($customer_name as $customer1)
									            <option data-tokens="{{$customer1->customer_name}}" value="{{$customer1->customer_name}}">{{$customer1->customer_name}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="assigned_to" id="assigned_to" data-live-search="true" title="Assigned To">
									    @if (count($engineers) > 0)
									        @foreach ($engineers as $engineer)
									            <option data-tokens="{{$engineer->assigned_to}}" value="{{$engineer->assigned_to}}">{{ucwords($engineer->assigned_to)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="status" id="status" title="Status">
										<option value="done">Done</option>
									    <option value="granted">Granted</option>
									    <option value="rejected">Rejected</option>
									    <option value="pending">Pending</option>  
									</select>
								</td>
								<td>
									<input placeholder="Refund Requested Date" class="form-control" type="text" onfocus="(this.type='date')" name="generated_date" onblur="(this.type='text')">
								</td>
								<td>
									<button type="submit" name="filter" class="btn btn-success">Search</button>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
			<div class="col-md-3 col-sm-3"></div>
			<div class="col-md-2 col-sm-2">
				<div class="well text-center">
					<a href="/exportRefunds" class="btn btn-warning">Export</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				@if (count($refunds) > 0)
					<div class="panel panel-default">
						<div class="panel-heading text-center"><b>Refunds</b></div>
						<div class="panel-body table-responsive">
							<form action="/actOnRefunds" method="post">
								{{csrf_field()}}
								<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
									<tr>
										<th>Sr. No</th>
										<th>Customer Id</th>
										<th>Customer Name</th>
										<th>Mode Of Payment</th>
										<th>Bank Name</th>
										<th>Account Number</th>
										<th>Bank Branch</th>
										<th>IFSC Code</th>
										<th>Amount</th>
										<th>Reason</th>
										<th>Mail Date</th>
										<th>Status</th>
										<th>Rejection Note</th>
										<th>UTR No</th>
										<th>Assigned To</th>
										<th>Generated By</th>
										<th>Generated Date</th>
										<th>Acted By</th>
										@if (Auth::user()->user_type == 'admin')
											<th>Grant</th>
											<th>Reject</th>
											<th>Delete</th>
										@endif
										<!--<th>UTR</th>-->
									</tr>
									<tr>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    <td></td>
					                    @if (Auth::user()->user_type == 'admin')
					                      <td>
					                      	<input type="checkbox" id="grantCkbCheckAll" />
					                      </td>
					                      <td></td>
					                      <td>
					                      	<input type="checkbox" id="deleteCkbCheckAll"/></td>
					                    @endif
					                </tr> 
									@foreach ($refunds as $refund)
										<tr>
											<td>{{$loop->iteration}}</td>
											<td>{{ucwords($refund->customer_id)}}</td>
											<td>{{ucwords($refund->customer_name)}}</td>
											<td>{{ucwords($refund->mode_of_payment)}}</td>
											<td>{{ucwords($refund->bank)}}</td>
											<td>{{ucwords($refund->account_no)}}</td>
											<td>{{ucwords($refund->branch)}}</td>
											<td>{{ucwords($refund->ifsc_no)}}</td>
											<td>{{ucwords($refund->refund_amount)}}</td>
											<td>{{ucwords($refund->reason)}}</td>
											<td>{{ucwords($refund->mail_date)}}</td>
											<td>{{ucwords($refund->refund_status)}}</td>
											<td>{{$refund->rejection_note}}</td>
											<td>
												{{ucwords($refund->utr_no)}}
												@if ($refund->utr_no != 'NA' && ($refund->refund_status == 'granted' || $refund->refund_status == 'done'))
													<a class="btn btn-warning btn-sm pull-right" style="color: white;" data-toggle="modal" data-target="#updateUtr" id="{{$refund->id}}" onclick="utr(this.id)">
														<img src="/storage/images/pencil.png" height="13px">
													</a>
												@endif
											</td>
											<td>{{ucwords($refund->assigned_to)}}</td>
											<td>{{ucwords($refund->generated_by)}}</td>
											<td>{{$refund->created_at}}</td>
											<td>{{ucwords($refund->granted_by)}}</td>
											@if (Auth::user()->user_type == 'admin')
												<td>
													@if ($refund->refund_status != 'done')
														<input type="checkbox" name="grantRefund[]" value="{{$refund->id}}" class="grantCheckBox">
													@endif
												</td>
												<!--<td>
													<input type="checkbox" name="rejectRefund[]" value="{{$refund->id}}">
												</td>-->
												<td>
													@if ($refund->refund_status != 'done')
														<a class="btn btn-primary btn-sm" style="color: white;" data-toggle="modal" data-target="#rejectRefund" id="{{$refund->id}}/{{$refund->customer_id}}" onclick="clck(this.id)">Reject</a>
													@endif
												</td>
												<td>
													<input type="checkbox" name="deleteRefund[]" value="{{$refund->id}}" class="deleteCheckBox">
												</td>
											@endif
											<!--<td>
												@if ($refund->utr_no != 'NA')
													<a class="btn btn-primary btn-sm" style="color: white;" data-toggle="modal" data-target="#updateUtr" id="{{$refund->id}}" onclick="clck(this.id)">UTR</a>
												@else
													NA
												@endif
											</td>-->
										</tr>
									@endforeach
									@if (Auth::user()->user_type == 'admin')
										<tr>
											<td colspan="21">
												@if (Auth::user()->user_type == 'admin')
													<input type="hidden" name="granted_by" value="{{auth()->user()->name}}">
													<input type="submit" class="btn btn-danger pull-right" name="action" value="Submit">
												@endif
											</td>
										</tr>	
									@endif
								</table>
							</form>	
						</div>
					</div>
					@else
					<h1 class="text-center">NO DATA FOUND</h1>
				@endif
				<div class="text-center">{{$refunds->links()}}</div>
			</div>
		</div>
	</div>
	

	<!-- Modal -->
	  <div class="modal fade" id="rejectRefund" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Reject Extension</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/rejectRefund" method="post">
					{{csrf_field()}}
					<table class="table table-striped">
						<tr class="form-group">
							<td><label>Customer Id:</label></td>
							<td>
								<input type="text" name="customer_id" class="form-control" readonly="true" id="customer_id2">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Reason:</label></td>
							<td>
								<textarea id="rejection_note" class="form-control" name="rejection_note" rows="4" cols="50" required="true">
								</textarea>
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Rejected By</label></td>
							<td>
								<input type="text" name="rejected_by" class="form-control" value="{{auth()->user()->name}}" readonly="true">
							</td>
						</tr>
						<tr class="form-group">
							<td>
								<input type="hidden" name="refund_id" id="refund_id1">
							</td>
							<td>
								<input type="submit" class="btn btn-danger" value="Reject">
							</td>
						</tr>
					</table>
				</form>
	        </div>
	        </div>
	      </div>
	      
	    </div>
	  </div>


	<!-- Modal -->
	  <div class="modal fade" id="updateUtr" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Enter UTR No</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/updateUtr" method="post">
					{{csrf_field()}}
					<table class="table table-striped">
						<tr class="form-group">
							<td><label>Enter UTR No:</label></td>
							<td>
								<input type="text" name="utr_no" class="form-control" required="true" id="utr_no">
							</td>
						<tr class="form-group">
							<td>
								<input type="hidden" name="refund_id" id="refund_id">
							</td>
							<td>
								<input type="submit" class="btn btn-success" value="Update UTR">
							</td>
						</tr>
					</table>
				</form>
	        </div>
	        </div>
	      </div>
	      
	    </div>
	  </div>
	
	<script type="text/javascript">
		function clck(id)
		{	
			var data = id.split('/')
			console.log(id)
			document.getElementById("refund_id1").value = data[0]
			document.getElementById("customer_id2").value = data[1]

		}
	</script>

	<script type="text/javascript">
		function utr(id)
		{
			document.getElementById("refund_id").value = id

		}
	</script>	

	<script type="text/javascript">
		//select all grant checkbox 
		$(document).ready(function () {
		    $("#grantCkbCheckAll").click(function () {
		        $(".grantCheckBox").prop('checked', $(this).prop('checked'));
		    });
		    
		    $(".grantCheckBox").change(function(){
		        if (!$(this).prop("checked")){
		            $("#grantCkbCheckAll").prop("checked",false);
		        }
		    });
		});
	</script>

	<script type="text/javascript">
		//select all delete checkbox 
		$(document).ready(function () {
		    $("#deleteCkbCheckAll").click(function () {
		        $(".deleteCheckBox").prop('checked', $(this).prop('checked'));
		    });
		    
		    $(".deleteCheckBox").change(function(){
		        if (!$(this).prop("checked")){
		            $("#deleteCkbCheckAll").prop("checked",false);
		        }
		    });
		});
	</script>
@endsection