@extends('layouts.app')

@section('title', 'List Down Areas')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="well">
					<form action="/listDownAreas" method="get">	
						<table class="table-condensed">
							<tr class="form-group">
								<td>
									<select class="form-control selectpicker" name="downArea" id="downArea" data-live-search="true" title="Down Area">
									    @if (count($areas) > 0)
									        @foreach ($areas as $area)
									            <option data-tokens="{{$area->area}}" value="{{$area->area}}">{{ucwords($area->area)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="assigned_to" id="assigned_to" data-live-search="true" title="Assigned To">
									    @if (count($engineers) > 0)
									        @foreach ($engineers as $engineer)
									            <option data-tokens="{{$engineer->assigned_to}}" value="{{$engineer->assigned_to}}">{{ucwords($engineer->assigned_to)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<select class="form-control selectpicker" name="reason" id="reason" data-live-search="true" title="Reason">
									    @if (count($reasons) > 0)
									        @foreach ($reasons as $reason)
									            <option data-tokens="{{$reason->reason}}" value="{{$reason->reason}}">{{ucwords($reason->reason)}}</option>
									        @endforeach     
									    @endif  
									</select>
								</td>
								<td>
									<input placeholder="Down Date" class="form-control" type="text" onfocus="(this.type='date')" name="downDate" onblur="(this.type='text')">
								</td>
								<td>
									<button type="submit" name="filter" class="btn btn-success">Search</button>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				@if (count($downAreas) > 0)
					<div class="panel panel-default">
						<div class="panel-heading text-center"><b>Down Areas</b></div>
						<div class="panel-body table-responsive">
							<table class="table table-striped table-condensed table-bordered" style="border: 1px solid #ccc;">
								<tr>
									<th>ID</th>
									<th>Area Name</th>
									<th>Reason</th>
									<th>Down Date</th>
									<th>TAT</th>
									<th>Assigned To</th>
									<th>Generated By</th>
									<th>Close</th>
								</tr>
								@foreach ($downAreas as $downArea)
									<tr>
										<td>{{$downArea->id}}</td>
										<td>{{ucwords($downArea->area)}}</td>
										<td>{{ucwords($downArea->reason)}}</td>
										<td>{{ucwords($downArea->down_day_time)}}</td>
										<td>{{ucwords($downArea->tat)}}</td>
										<td>{{ucwords($downArea->assigned_to)}}</td>
										<td>{{ucwords($downArea->generated_by)}}</td>
										<td>
											<button class="btn btn-danger btn-sm" style="color: white;" data-toggle="modal" data-target="#close_job" id="{{$downArea->id}}" value="{{$downArea->area}}" onclick="clck(this.id, this.value)">X</button>
										</td>
									</tr>
								@endforeach
							</table>
						</div>
					</div>
					@else
						<h2 class="text-center">NO DATA FOUND</h2>	
				@endif
				<div class="text-center">{{$downAreas->links()}}</div>	
			</div>
		</div>
	</div>
	<!-- Modal -->
	  <div class="modal fade" id="close_job" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Close Job</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/closeDownArea" method="post">
					{{csrf_field()}}
					<table class="table table-striped">
						<tr class="form-group">
							<td><label>ID</label></td>
							<td>
								<input type="text" name="downAreaId" class="form-control" readonly="true" id="downAreaId">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Down Area:</label></td>
							<td>
								<input type="text" name="downArea" class="form-control" readonly="true" id="downArea1">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Up day:</label></td>
							<td>
								<input type="datetime-local" name="upTime" class="form-control" id="upTime">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Closed By</label></td>
							<td>
								<input type="text" name="closed_by" class="form-control" value="{{auth()->user()->name}}" readonly="true">
							</td>
						</tr>
						<tr class="form-group">
							<td></td>
							<td>
								<input type="submit" class="btn btn-success" value="Close">
							</td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>
	  <script type="text/javascript">
	  	function clck(id, area)
	  	{
	  		document.getElementById("downAreaId").value = id
	  		document.getElementById("downArea1").value = area
	  	}
	  </script>
@endsection