@extends('layouts.app')

@section('title', 'List Down Areas')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center"><b>Feasible Areas</b></div>
					<div class="panel-body table-responsive">
						<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
							@if (count($feasibleAreas) > 0)
								<tr>
									<th>Sr. No</th>
									<th>Reseller Name</th>
									<th>Building</th>
									<th>Society</th>
									<th>Area</th>
									<th>City</th>
									<th>Switch Location</th>
									<th>Contact Person Name</th>
									<th>Contact Person Number</th>
									<th>Generated By</th>
								</tr>
								@foreach ($feasibleAreas as $feasibleArea)
									<tr>
										<td>{{$loop->iteration}}</td>
										<td>{{ucwords($feasibleArea->reseller_name)}}</td>
										<td>{{ucwords($feasibleArea->building)}}</td>
										<td>{{ucwords($feasibleArea->society)}}</td>
										<td>{{ucwords($feasibleArea->area)}}</td>
										<td>{{ucwords($feasibleArea->city)}}</td>
										<td>{{ucwords($feasibleArea->switch_location)}}</td>
										<td>
											{{ucwords($feasibleArea->contact_person_name)}}
										</td>
										<td>
											{{ucwords($feasibleArea->contact_person_number)}}
										</td>
										<td>{{ucwords($feasibleArea->generated_by)}}</td>
									</tr>
								@endforeach
							@endif
							</table>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection