@extends('layouts.app')

@section('title', 'Extension')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading text-center"><b>Extensions</b></div>
					<div class="panel-body table-responsive">
						<table class="table table-striped table-bordered" style="border: 1px solid #ccc;">
							@if (count($extensions) > 0)
								<tr>
									<th>Sr .No</th>
									<th>Customer Id</th>
									<th>Complaint Date</th>
									<th>Expiry Date</th>
									<th>Reason</th>
									<th>Extension Days</th>
									<th>Assigned To</th>
									<th>Status</th>
									<th>Generated By</th>
									<th>Extension status</th>
								</tr>	
								@foreach ($extensions as $extension)
									<tr>
										<td>{{$loop->iteration}}</td>
										<td>{{ucwords($extension->customer_id)}}</td>
										<td>{{ucwords($extension->complaint_date)}}</td>
										<td>{{ucwords($extension->expiry_date)}}</td>
										<td>{{ucwords($extension->reason)}}</td>
										<td>{{ucwords($extension->extension_day)}}</td>
										<td>{{ucwords($extension->assigned_to)}}</td>
										<td>{{ucwords($extension->status)}}</td>
										<td>{{ucwords($extension->generated_by)}}</td>
										<td>
											<button class="btn btn-danger btn-sm" style="color: white;" data-toggle="modal" data-target="#change_status" id="{{$extension->id}}" value="{{$extension->customer_id}}/{{$extension->extension_day}}" onclick="clck(this.id, this.value)">Status</button>
										</td>
									</tr>
								@endforeach
							@endif
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
		<!-- Modal -->
	  <div class="modal fade" id="change_status" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title text-center"><b>Change Extension Status</b></h4>
	        </div>
	        <div class="modal-body">
				<form action="/changeExtensionStatus" method="post">
					{{csrf_field()}}
					<table class="table table-striped">
						<tr class="form-group">
							<td><label>Complaint Id:</label></td>
							<td>
								<input type="text" name="extension_id" class="form-control" readonly="true" id="extension_id">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Customer Id:</label></td>
							<td>
								<input type="text" name="customer_id" class="form-control" readonly="true" id="customer_id">
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Extension Days:</label></td>
							<td>
								<input type="number" name="extension_days" class="form-control" id="extension_days" readonly="true">
							</td>
						</tr>
						<tr class="fomr-group">
							<td><label>Extension Status</label></td>
							<td>
								<select class="selectpicker form-control" name="extension_status" required="true" title="Select Status">
									<option value="granted">Grant</option>
									<option value="rejected">Reject</option>
								</select>
							</td>
						</tr>
						<tr class="form-group">
							<td><label>Extension Granted By</label></td>
							<td>
								<input type="text" name="extension_granted_by" class="form-control" value="{{auth()->user()->name}}" readonly="true">
							</td>
						</tr>
						<tr class="form-group">
							<td></td>
							<td>
								<input type="submit" class="btn btn-success" value="Submit">
							</td>
						</tr>
					</table>
				</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
	  </div>
	  <script type="text/javascript">
	  	function clck(id, value)
	  	{
	  		var data = value.split("/")
	  		document.getElementById("extension_id").value = id
	  		document.getElementById("customer_id").value = data[0]
	  		document.getElementById("extension_days").value = data[1]
	  	}
	  </script>
@endsection