@extends('layouts.app')

@section('title', 'List Feasible Areas')

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				@if (count($downAreas) > 0)
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<b>Closed Down Areas</b>
						</div>
						<div class="panel-body table-responsive">
							<form action="/deleteClosedDownAreas" method="post">
								{{csrf_field()}}
								<table class="table table-striped table-condensed table-bordered" style="border: 1px solid #ccc;">
									<tr>
										<th>ID</th>
										<th>Area Name</th>
										<th>Reason</th>
										<th>Down Date Time</th>
										<th>TAT</th>
										<th>Assigned To</th>
										<th>Generated By</th>
										<th>Up Date Time</th>
										<th>Closed By</th>
										@if (Auth::user()->user_type == 'admin')
											<th>Delete</th>
										@endif
									</tr>
									@foreach ($downAreas as $downArea)
										<tr>
											<td>{{$downArea->id}}</td>
											<td>{{ucwords($downArea->area)}}</td>
											<td>{{ucwords($downArea->reason)}}</td>
											<td>{{ucwords($downArea->down_day_time)}}</td>
											<td>{{ucwords($downArea->tat)}}</td>
											<td>{{ucwords($downArea->assigned_to)}}</td>
											<td>{{ucwords($downArea->generated_by)}}</td>
											<td>{{ucwords($downArea->up_day_time)}}</td>
											<td>{{ucwords($downArea->closed_by)}}</td>
											@if (Auth::user()->user_type == 'admin')
												<td>
													<input type="checkbox" name="delete_{{$loop->iteration}}" value="{{$downArea->id}}">
												</td>
											@endif
										</tr>
									@endforeach
								</table>
								@if (Auth::user()->user_type == 'admin')
									<input type="submit" name="deleteBtn" value="Delete" class="btn btn-danger pull-right">
								@endif
							</form>				
						</div>
					</div>
					@else
						<h2 class="text-center">NO DATA FOUND</h2>	
				@endif
				<div class="text-center">{{$downAreas->links()}}</div>
			</div>
		</div>
	</div>
@endsection